
ROLE_CHOICES = ['1', '2', '3', '4', '5']
Gender_CHOICES = ['M', 'F', 'B']
FIELD_IS_NOT_ALLOWED = ' is not allowed.'
USER_TYPE_ADMIN = 1
USER_TYPE_Employee = 2

BOOKING_FROM_PLATFORM = ['ANDROID', 'iOS','VENDOR_PORTAL']

bookingStatusEnums = {
    'COMPLETED': 'COMPLETED',
    'ARRIVED': 'ARRIVED',
    'CONFIRMED': 'CONFIRMED',
    'NO_SHOW': 'NO_SHOW',
    'CANCELED': 'CANCELED',
    'PAYMENT_PENDING': 'PAYMENT_PENDING',
}

